# Generated by Django 4.0.5 on 2022-07-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Defectivegood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodname', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Foods', 'Foods'), ('Detergents', 'Detergents'), ('Kitchen-ware', 'Kitchen-ware'), ('Toys', 'Toys')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['goodname'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_product', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Foods', 'Foods'), ('Detergents', 'Detergents'), ('Kitchen-ware', 'Kitchen-ware'), ('Toys', 'Toys')], max_length=20, null=True)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordered_product'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Foods', 'Foods'), ('Detergents', 'Detergents'), ('Kitchen-ware', 'Kitchen-ware'), ('Toys', 'Toys')], max_length=20, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20, null=True)),
                ('buying_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('expiry_date', models.DateTimeField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
    ]
