# Generated by Django 4.0.5 on 2022-07-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='AdminId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
