# Generated by Django 4.0.5 on 2022-07-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0003_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectivegood',
            name='clerk',
        ),
    ]
