# Generated by Django 4.0.5 on 2022-07-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0004_remove_defectivegood_clerk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='clerk',
        ),
    ]
