# Generated by Django 4.0.5 on 2022-07-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localapp', '0006_defectivegood_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectivegood',
            name='product',
        ),
    ]
